_BASE_: [
  '../datasets/coco_detection_fewshotlogo.yml',
  '../runtime.yml',
  './_base_/ppyolo_r50vd_dcn.yml',
  './_base_/optimizer_2x.yml',
  './_base_/ppyolo_reader_logo.yml',
]

snapshot_epoch: 5
weights: output/ppyolo_r50vd_dcn_2x_coco_fewshotlogo/model_final
