_BASE_: [
  '../datasets/coco_detection_fewshotlogo2.yml',
  '../runtime.yml',
  './_base_/optimizer_300e_fewshotlogo.yml',
  './_base_/ppyoloe_crn.yml',
  './_base_/ppyoloe_reader.yml',
]

log_iter: 100
snapshot_epoch: 10
weights: output/ppyoloe_crn_m_300e_coco_fewshotlogo/model_final

pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/CSPResNetb_m_pretrained.pdparams
depth_mult: 0.67
width_mult: 0.75

TrainReader:
  batch_size: 16

LearningRate:
  base_lr: 0.035
