metric: COCO
num_classes: 50

TrainDataset:
  !COCODataSet
    image_dir: /home/zhangxin/data_public/tianchi_det/train/images
    anno_path: /home/zhangxin/data_public/tianchi_det/train/annotations/instances_train2017_train.json
    dataset_dir: dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: /home/zhangxin/data_public/tianchi_det/train/images
    anno_path: /home/zhangxin/data_public/tianchi_det/train/annotations/instances_train2017_val.json
    dataset_dir: dataset/coco

TestDataset:
  !ImageFolder
    anno_path: /home/zhangxin/data_public/tianchi_det/val/annotations/instances_val2017.json
    dataset_dir: dataset/coco
